binaryberry/seal

- bin/custom.rb
- The daily roundup of PRs was missing one of mine because the
Business Support API wasn't tracked.
> Add Business Support API to the list of Custom's apps

- Gemfile
- config/alphagov.yml
- lib/message_builder.rb
Seal won't get angry if you don't review pull requests at the weekend.
Upgraded to 2.1.2
Added repo for finding-things team
> Weekend unangry

- README.md
Q: Does this trigger a Travis CI build?
> A little README tidy-up

- README.md
- config/alphagov.yml
- config/envato.yml
- lib/github_fetcher.rb
- spec/github_fetcher_spec.rb
https://github.com/envato/seal/commit/a01ba9d869efa66748602b2f4a90f54b508e68a9 & https://github.com/envato/seal/commit/cc87861085b3c9d2d1dcecfbca8b1776d632edfc highlight that we should be comparing strings insensitively.
- Improve hiding of titles and labels.
- Simplify configuration files
> Case insensitivity

- README.md
- lib/github_fetcher.rb
- lib/message_builder.rb
- lib/slack_poster.rb
- spec/github_fetcher_spec.rb
- spec/message_builder_spec.rb
The Angry seal looks scarier, and thumbs up are tracked.
This is information is an important element of our review process - for
our largest app - whitehall - a PR is ready to merge when someone else
commented there was a thumbs up.
> Tracks thumbs up and makes seal angrier

- config/alphagov.yml
https://github.com/alphagov/govuk_message_queue_consumer is new and shiny and has many pull requests open.
Bonus seal gif:
> Add `govuk_message_queue_consumer` to finding things

- config/alphagov.yml
- Remove Mark Hurrell
- Add Stephen Richards
- Add Publishing API repository
> Update Finding Things team

- config/alphagov.yml
alext has left the team unfortunately.
> Update Finding Things team even more

- config/alphagov.yml
Core want to see Tommy's PRs to help with specialist-publisher rewrite, core and custom have new joiners.
> Update team members

- config/alphagov.yml
Adds the missing infra people.
Removes Langhorn.
> Move publishing platform seal to #platform-team

- config/alphagov.yml
@stephen-richards has left us, and @Davidslv has joined the team.
> Update team Finding Things

- config/alphagov.yml
I've removed them from the alphagov.yml
> Mark Sheldon and Tommy Palmer have gone :-(

- config/alphagov.yml
We want to ignore pull requests that have certain prefixes.
We <3 the Seal!
> Add ignore statuses to Specialist Publisher team

- config/alphagov.yml
> Add Tom and Russell to SP team

- config/alphagov.yml
Jon has joined the infrastructure team.
> Add jonauman to infra

- config/alphagov.yml
* Remove AndrewVos
* Add deborahchua
* Exclude a couple of repos which one of our team members spends a lot of time in but the service manual team can't help with
* Exclude WIP PRs.
> Alphagov service manual config

- README.md
I previewed it this time! I shall shame bell myself...
🔔 🔔 🔔
> Fix markdown syntax for config link in README

- config/alphagov.yml
> Add Oliver Byford (@36degrees) to Service Manual team

- config/alphagov.yml
Remove accounts for people who have left.  Add Caroline's github account.
> Update yaml to reflect new team members

- README.md
When installing the Seal recently I found a few parts of the process confusing, so I've clarified a couple of the points. 
1) It wasn't obvious that if you want to test the Seal in #angry-seal-bot-test, that the Slack webhook had to be pointing at the #angry-seal-bot-test channel, and not your eventual preferred channel.
2) I had never used Heroku before and was a bit confused as to what command I needed to put in the scheduler. I've added a tip to make it (I hope!) more obvious.
> Some small clarifications to the README

- config/alphagov.yml
Hello :wave: here are some changes from the Publishing Team
> Publishing Transfers

- config/alphagov.yml
Move Nick from Core to new team
> Create template consolidation team.

- config/alphagov.yml
> Goodbye @jackscotti

- config/alphagov.yml
I've just joined the Finding Things team.
> Add user suzannehamilton

- config/alphagov.yml
> Update Publishing Platform Team

- config/alphagov.yml
I normally use that as I feel it's less authoritarian and more self explanatory.
> Add REVIEW ONLY excluded title

- config/alphagov.yml
Hello Josh (@mcmillan) 👋 😄 
Bye Henry (@thehenster) 👋 😭
> Service Manual Team Changes

- config/alphagov.yml
I've just joined Finding Things.
> Add user alecgibson

- config/alphagov.yml
> Remove references to Shilpa

- config/alphagov.yml
We have a lot of PRs that have been reviewed but are waiting on
a department to fact check. These can take a long time. Adding
the label for Seal to filter these out.
> Add content tool exclusion label

- config/alphagov.yml
A misunderstanding on my part meant that we weren't filtering out PRs by label. *Sigh*.
> Actually filter labels

- config/alphagov.yml
Removed Jon from the team and added Ana and Sam. I also added some new messages.
> Added Ana, Sam and added a few messages

- config/alphagov.yml
Apologies, just a few more requests from the team.
> A few more messages

- config/alphagov.yml
Carlos and Doug have left 😢 
Michael was missing from this list.
> Streamlined publishing platform team

- config/alphagov.yml
Mo is mostly at email the coming weeks and Caroline has been for a couple of weeks now.
> Update Finding Things

- README.md
This makes two 2nd-level headings render as such
> Add required space after ^## in headers in README

- config/alphagov.yml
> Add search team

- config/alphagov.yml
> Remove Custom. Booooooooo

- config/alphagov.yml
We're now content transformation and navigation. Still in the same
channel though!
> Split Finding Things

- bin/afternoon_seal.sh
- bin/late_afternoon_seal.sh
- bin/morning_seal.sh
- config/alphagov.yml
Includes updates to the morning_seal and afternoon_seal scripts.
> Config changes to reflect new teams

- config/alphagov.yml
New team members have joined, we'd like to know about their PRs.
Add members github name and exclude titles for #templateconsolidation.
> Updated template consolidation team

- config/alphagov.yml
> Add Andrien to the Navigation team

- config/alphagov.yml
> Different channels for taxonomy & nav

- config/alphagov.yml
Matteo has moved from Worldwide Publishing to Content Tools
> Move mgrassotti

- bin/afternoon_seal.sh
- config/alphagov.yml
- Add @binaryberry 👋 
- Get quotes from the afternoon seal (from our team charter post its)
> Update search team

- config/alphagov.yml
> Remove me (issyl0) from Benchmarking and add to Infrastructure

- config/alphagov.yml
Katie has moved to another team in GDS and Andrien is joining Taxonomy.
> Update taxonomy team

- config/alphagov.yml
> Merge scrutineers back into taxonomy

- config/alphagov.yml
We're also modelling services, so need a Zoolander quote.
> Add some quotes to Benchmarking

- config/alphagov.yml
> Add Rosa-Fox to the search team

- config/alphagov.yml
> Add frontend-design team

- config/alphagov.yml
We need some more up to date quotes now a bunch of people have left. A mix of in-jokes, humourous, and inspiring.
> Update quotes and users

- config/alphagov.yml
> Update Content Tools members

- config/alphagov.yml
> Content API team is no more

- README.md
- bin/morning_seal.sh
Updates morning invite list 
Updates documentation to guide future users towards doing so
> Invite seal

- config/alphagov.yml
> Add Made Tech team

- bin/morning_seal.sh
- config/alphagov.yml
> Schedule Seal for Made Tech team

- config/alphagov.yml
So my PRs appear in the seal activity
> Add myself, adrianclay to madetech members

- README.md
- lib/github_fetcher.rb
- lib/seal.rb
- spec/github_fetcher_spec.rb
- spec/seal_spec.rb
Updating README with info for REPOS env vars
Let me know if there's any changes you need.
> Adding a feature to allow explicitly including github repositories

- config/alphagov.yml
We have a new Slack channel and everything.
> GOV.UK Infra leave GOV.UK

- config/alphagov.yml
> Add new members to frontend-design team

- config/alphagov.yml
The Start Pages team is no more :( It should be removed from the Seal...
> Remove Start Pages team

- bin/afternoon_seal.sh
- bin/morning_seal.sh
- config/alphagov.yml
This commit:
- alphabetises the config file
- removes an unused team
- changes a YAML key to match the Slack channel name
- ensures all teams have at least the morning seal, and those with quotes have the afternoon seal
> Tidy up teams

- config/alphagov.yml
The Content Tools team is no more. We are now...
Data Informed Content (Decisions|Insights)! Catchy!
> Convert Content Tools to Data Informed Content

- config/alphagov.yml
> Add James and SK to the Reliability Engineering team list

- config/alphagov.yml
We want to show [DO NOT MERGE] PRs in our review list.
We also want to show some mega-chag in our work.
> Update modelling-services config

- config/alphagov.yml
Also reorder team members and add some erudite seal quotes.
> Add selfthinker to modelling services

- bin/afternoon_seal.sh
- bin/morning_seal.sh
- config/alphagov.yml
Add the Licensify support team
> Add Licensing support team

- bin/morning_seal.sh
- config/alphagov.yml
> Remove email team

- bin/morning_seal.sh
- config/alphagov.yml
Replace the Taxonmomy team, as that is the one I'm on.
I hope I've got peoples GitHub details right...
> Update Seal configuration for Taxonomy Navigation

- config/alphagov.yml
> Update platform support team

- bin/morning_seal.sh
- config/alphagov.yml
> Remove superseded teams

- bin/afternoon_seal.sh
- bin/morning_seal.sh
- config/alphagov.yml
We have mostly joined the org pages team!
> The devs have left modelling services

- config/alphagov.yml
I need pull request reviews too!
> Add myself to taxonomy & porg teams

- config/alphagov.yml
> Add include_repos for data-gov-uk team
