config/config.yml

This repo is relevant to all teams and is currently missing from the the Seal's morning announcement. This commit adds it to both teams' lists of repos.

Add govuk-content-schemas to Core and Custom teams

---

README.md
config/envato.yml
lib/message_builder.rb
spec/message_builder_spec.rb

After I deployed https://github.com/binaryberry/seal/pull/8 , one of my colleagues pointed out that the angry seal was complaining about a PR that he'd written that day.
- Added the age to the PR presentation
- Filtered out PRs younger than 2 days old from angry seal messages
- Performed some pipeline refactoring
- Fixed a couple of display bugs

Don't get angry when PRs are under two days old

---

config/alphagov.yml

@jackscotti is also on the Finding Things team, but he's not on the list.

Add new member to team

---

README.md
config/envato.yml
lib/github_fetcher.rb
lib/message_builder.rb
lib/seal.rb
spec/github_fetcher_spec.rb
spec/message_builder_spec.rb

Context
-------
Now that the Seal has been working hard at Envato for a week, the biggest request from my team is to not mention PRs that are labelled 'wip'. 
"To be done:" has "do not display [DO NOT MERGE] pull requests"
Changes
-------
- Fetch labels for PRs from GitHub
- Include labels in pull request lines
- Make fetching labels optional since it's expensive
- Allow teams to exclude PRs with certain labels
- Allow hiding titles
- Update changelog
- Remove disused code

Do not display [DO NOT MERGE] / WIP pull requests

---

lib/message_builder.rb
spec/message_builder_spec.rb

- This was inconsistent with the normal Seal new lines between the PRs
and the ending message.

Remove a double new line after the PRs on the Angry Seal message

---

Gemfile
Gemfile.lock

Context
-------
````
[Tue 15/08/11 21:15 AEST][s018][x86_64/darwin14.3.0/14.4.0][5.0.8]
<paj@clacks:~/src/seal>
zsh/2 6997  (git)-[discovery]-% bundle exec bin/angry_seal.rb discovery
/Users/paj/src/seal/lib/github_fetcher.rb:54:in `labels': undefined method `number' for [:message, "Moved Permanently"]:Array (NoMethodError)
from /Users/paj/src/seal/lib/github_fetcher.rb:64:in `hidden_labels'
from /Users/paj/src/seal/lib/github_fetcher.rb:59:in `hidden?'
from /Users/paj/src/seal/lib/github_fetcher.rb:24:in `block (2 levels) in list_pull_requests'
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
from /opt/rubies/2.1.2/lib/ruby/gems/2.1.0/gems/sawyer-0.6.0/lib/sawyer/resource.rb:125:in `each'
from …
```

Upgrade Octokit to v4

---

README.md
lib/seal.rb
spec/seal_spec.rb

Context
=======
I'm lazy.
Much like I don't want to add and remove people as they join and leave a project (see https://github.com/binaryberry/seal/commit/0b59c77781b79bd06d38dc54898266892d0e85eb), I don't want to have to maintain Heroku schedulers (as neat as they are) each time somebody adds or removes a team.
Change
======
If a team is not specified, Seal will bark at all teams in its config. If a team is provided, Seal will just bark at that one, as before.

Bark at each team in the config if none provided

---

README.md
bin/angry_seal.rb
bin/seal.rb
lib/message_builder.rb
lib/seal.rb
spec/message_builder_spec.rb
spec/seal_spec.rb
spec/slack_poster_spec.rb

At the moment, there is one angry_seal task to monitor old PRs, and an informative seal task to publish ongoing PRs. This means where there are old and new PRs, we get 2 seals posting immediately after one another. These changes ensure only one seal needs to post each day:
- If there are no PRs that day, seal of approval
- If there are PRs that have been updated less than 2 days ago,
informative seal
- If there is at least one PR that has been updated over 2 days ago,
angry seal, which lists both old PRs and (less angrily) the recent ones

Have seal mood depend on number & age of PRs

---

config/alphagov.yml

@mobaig isn't in the list, so his pull requests aren't shown by the seal.

Add mobaig to team finding things

---

README.md
app.json
lib/seal.rb

In order to deploy without modifying the config in the repo I added a number of
additional environment variables:
SLACK_CHANNEL
GITHUB_REPOS
GITHUB_MEMBERS
GITHUB_USE_LABELS
GITHUB_EXCLUDE_LABELS
GITHUB_EXCLUDE_TITLES
This only works in simple team structures (one channel for the whole team)

Add Heroku deploy button

---

config/alphagov.yml

Finding Things also works on the content-store sometimes.
To make scanning the configs easier, I've sorted them alphabetically.

Add content-store for Finding Things

---

Gemfile
Gemfile.lock
Guardfile
spec/seal_spec.rb

Since https://github.com/binaryberry/seal/pull/26 , `Seal` no longer cares about `mood`.
- Remove `mood` from `Seal`'s spec
- Add [Guard](http://code.tutsplus.com/tutorials/testing-your-ruby-code-with-guard-rspec-pry--cms-19974) to speed up TDD cycle.

Remove dead code

---

app.json

Heroku Scheduler is used to run the bin scripts at regular intervals

Added Heroku Scheduler to Heroku Deploy button

---

lib/seal.rb
spec/seal_spec.rb

Context
-------
https://github.com/binaryberry/seal/pull/31 [broke our CI](https://travis-ci.org/envato/seal/builds/83603855) when I [merged it into our own organisation's repo](https://github.com/envato/seal/pull/14).
It didn't break CI upstream because that CI environment sets [`export SEAL_ORGANISATION=alphagov`]( https://travis-ci.org/binaryberry/seal/builds/82113946#L89).
Change
------
Rather than enforce setting environment variables to run the specs, I've
stubbed `ENV`. This gives us greater control over the behaviour of the
class under test allowing us to check the file that would be loaded.
Considerations
--------------
The behaviour of the class using environment-based configuration for a
team remains untested.

Fix Seal spec

---

Gemfile
Gemfile.lock
Rakefile
app.json

Context
-------
We use Seal a long way from UTC, which means the age of PRs, weekends,
_et cetera_ need to be calculated taking our offset into account.
Change
------
- Use app.json to document TZ usage.
- Use jsonlint in CI to ensure app.json is valid.
See also
--------
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Add TZ to optional environment variables

---

app.json

That information can be included in the config yml file
so shouldn't be required for the Heroku deploy button.

Make Github repos and Slack channel optional

---

Gemfile
Gemfile.lock
server.rb

This is to work with alphagov/gds-hubot and allow the Seal report to be produced via Hubot.

Add API endpoint

---

app.json
config/alphagov.yml
config/envato.yml
lib/github_fetcher.rb
lib/seal.rb
spec/github_fetcher_spec.rb
spec/seal_spec.rb
spec/spec_helper.rb

Currently, the seal loops through all repos and fetches all pull requests. We could replace this with the issue search: https://developer.github.com/v3/search/#search-issues
This will return all open PRs in all alphagov repos. It uses the same search syntax as github.com.
This means 1) we can get rid of the repos in the configuration, 2) new repos are added automatically, 3) we save a bunch of requests.
Closes: #52

Use github search to power pull request search

---

lib/github_fetcher.rb
lib/slack_poster.rb
spec/github_fetcher_spec.rb

It turns out `#search_issues` returns 30 results per default. This caused the seal to report on only the 30 most recent pull requests in the organisation.
This commit fixes this by increasing that number to 100, the maximum of requests per page according to the API docs (and experimentation). This should take care of most missing pull requests.
Also adds a option (`DRY=1`) to the seal so that testing is a little easier.
Closes #73

Let seal see more pull requests

---

lib/github_fetcher.rb
spec/github_fetcher_spec.rb

The auto-paginate method needed to be called on the instance of the client
instead of the Octokit class. This means it's no longer necessary to specify
the 100 items limit as the client will go through all the pages, and set the 100
items limit per page by default.
This means this will now pull all the PRs of an organisation, not just the 100 most recent ones!
cc @tijmenb @johnsyweb @boffbowsh @monfresh

Fix auto-pagination bug

---

config/alphagov.yml

my github account name uses the german spelling of christopher

fix typo in my name

---

config/alphagov.yml

We're finding the seal helpful but we'd also like somewhere to hide unfinished code from its gaze.

Ignore unfinished PRs for the govuk-infrastructure team

---

config/alphagov.yml

The "exclude_titles" in specialist-publisher was not indented correctly, which broke several seals.
YAML is very unforgiving with indentation.
cc @sihugh  (but the seal still :heart: s you!)

Fix yml indentation

---

bin/afternoon_seal.sh
bin/late_afternoon_seal.sh
bin/morning_seal.sh

Hey @binaryberry,
Thanks for taking time to maintain seal :)
I just wanted to show you that bash supports arrays which you can use to iterate instead of creating several repeated lines.
Also since you not in ruby but in bash, you can dismiss the double '`' characters around the command you want to execute.
They are normally used when you need the output, for example
```
vim `which ruby`
vim $(which ruby)
```
My suggestion would be for you to play around with [ARGV](http://jnoconor.github.io/blog/2013/10/13/a-short-explanation-of-argv/) and make `./bin/seal.rb` receive a list of teams and the given command (`quotes` in your case) and iterate those in ruby, maybe something for you to think about...

Refactor seal bash scripts

---

config/alphagov.yml
lib/github_fetcher.rb
lib/seal.rb
spec/github_fetcher_spec.rb
spec/seal_spec.rb

I'm in the custom team but I also happen to work on a repo that lives in the same github organisation, but is not of interest to anyone else in the team.  It would be nice to filter that repo out of our seal to avoid being barked at when there's nothing anyone in the team can do as they don't have responsibility for that repo.  This PR adds that functionality and configures the custom team to ignore that repo.

Allow excluding prs based on repo

---

config/alphagov.yml

we are only getting angry seals now for PR on other team's repo.

remove non-active team members of specialist-publisher

---

README.md

It wasn't immediately obvious to me that the alphagov config was in binaryberry/seal. This hopefully gives alphagovers a hint and also will help people outside alphagov who are trying it out.

Describe the naming convention for the config file

---

config/alphagov.yml

~~one for github dot com and dot gds~~
Removed incorrect `github.gds` username and add correct `github.com` username for new member on specialist-publisher team.

Chris has two different github user name

---

lib/message_builder.rb
server.rb
spec/message_builder_spec.rb

Also adds a message that confirms the url has been hit (for debugging
purposes) and requests secret key to trigger the seal.
I've tested these changes locally and by deploying the branch, then triggering hubot through the bin/hubot console, and all seems to work well.
I'll be merging this once my PR on gds-hubot has been merged, so I can try it live.

Add hubot integration

---

config/alphagov.yml
npm-debug.log

A space was missing before the channel key of the template consolidation team, which made all the seal jobs fail. Oh, YAML.
Adding a yaml linter to the CI pipeline would be a good idea, but I am hoping to stop using YAML in the future and store the team's configuration in a database so I'll put up with the mistake risk for now, unless someone wants to open a PR.

Fix yaml spacing error

---

config/alphagov.yml

We've recently bid adieu to @h-lame, but we've gained @whoojemaflip and @deborahchua.
As Murray's no longer in the team, we probably don't need to ignore e-petitions any more.

Change Custom team membership list

---

config/alphagov.yml

The pop-up team and email team have been created. Daz has joined infrastructure.

Create 2 new teams, move people

---

config/alphagov.yml

This is causing lots of alerts in the service manual channel about frontend alpha PRs, as the service manual team doesn't want to know about these - remove gemmaleigh from the list of members.

Remove gemmaleigh from the service manual team

---

config/alphagov.yml

When [Jen regenerated into Shilpa][1], we experienced a rift in the space-time continuum resulting in them both having corporeal representations in the same plane of existence (the seal).  This must be resolved prior to the annual multiverse reconciliation date or we may all be annihilated.
There can be only one.
[1]: https://github.com/binaryberry/seal/commit/60500a4f9f7fe7184cf4ecb5d5a729299b856dcf

Eliminate Jen's vestigial remains

---

bin/afternoon_seal.sh
bin/morning_seal.sh
config/alphagov.yml

The Content Tools team now look after a bunch of apps that many others issue PRs on. We need to be more aware of these and have Seal prompt us.
I’ve added the team to the `config.yml` with our current members, the labels I think we’d want to ignore (Do not merge) and have stolen the Core Format team’s charter for quotes.
I think I've done this right - I couldn't see anything else where I'd need to configure.

Add Content Tools

---

lib/github_fetcher.rb
lib/message_builder.rb
spec/github_fetcher_spec.rb
spec/message_builder_spec.rb

Many teams are now using Github's new review workflow, where you
explicitly approve a PR rather than marking it with a +1. This is now
supported in their API as a preview function via a specific media type
header.
This change adds a green check mark for PRs that are approved in this
way.

Show check mark when PRs are approved.

---

config/alphagov.yml

I don’t know how I didn’t spot this but I missed out a flag to make
Seal exclude the labels. I’ve also tidied up my team’s quotes to be less
plagiaristic.

Set flag to exclude labels

---

bin/morning_seal.sh
config/alphagov.yml

We are writing code, and we are more people now :)

Re-add email team to alphagov config

---

spec/config_spec.rb

This adds a test for our config. Makes sure that we don't put in invalid YAML.

Add spec for alphagov.yml

---

config/alphagov.yml

This prevents `seal me up` from working.

Fix taxonomy team name

---

config/alphagov.yml

Remove the people that have changed roles from the govuk-infrastructure
team as we don't need to see their PRs

The team roster has changed slightly.

---

bin/morning_seal.sh
config/alphagov.yml

Combination of developers from Content History and Scrutineers, as we'll be
sharing a trello board and channel be good to keep the PRs together.

Add hold government to account team

---

config/alphagov.yml

The mismatch prevents the "seal me up" command from working.
See https://github.com/binaryberry/seal/pull/173

Make the team name match slack for search

---

config/alphagov.yml

The seal was not returning my PRs - I think because the filter
is case sensitive.

Make seal pick up my PRs

---

config/alphagov.yml

The navigation team would like to see all PRs that are open, apart from
WIP PRs, so that we can start early reviews. Most times the DO NOT MERGE
tag is only there to coordinate deploys or get early feedback, so it's
important to see that.

Show PRs that are ready for review

---

config/alphagov.yml

He has moved from Holding Government to Account to Worldwide Publishing.

Move Bevan to his new team

---

config/alphagov.yml

The Worldwide Publishing team has ended, but most people have transferred over to the Email team.

Morph Worldwide Publishing to Email

---

server.rb

I wanted to make Seal respond to on demand request. So I added a slack `slash command` to my team's slack. https://api.slack.com/custom-integrations/slash-commands
The problem with the current implementation is that our Seal takes its time to answer, so Slack times out without an answer showing an error to the user. With this change, the invoker receives a `Just a second...` message while the list of PRs is built.
Tested on heroku. Works great.

Add async calculation for server call

---

config/alphagov.yml

Swap @cbaines with @andrewgarner on Taxonomy.
Leave @alecgibson on Navigation also as they are only paused.

Add new devs to Content Tools

---

bin/morning_seal.sh

Remove Worldwide Publishing from morning seal

---

config/alphagov.yml

Chris is now a part of the Email team.

Add Chris Patuzzo to Email team

---

config/alphagov.yml

This is to reflect the recent changes in the team structure.
Are you happy with this @leenagupte ?

Replace the navigation team with scrutineers

---

config/alphagov.yml

Scruitineers now has its own section so Leena and Bevan are there, and
Katie has joined.

Change hold-gov-to-account team to content-api

---

config/alphagov.yml

For the taxonomy team, as it would be useful to get the seal to ignore some Pull Requests, but none of the other exclude titles are applicable.

Add "[SEAL IGNORE]" to exclude_titles

---

bin/morning_seal.sh
config/alphagov.yml

The template consolidation team has become the publishing-frontend team, and has new members. Although the search-team had the correct name in the config, that name also needed to be corrected in `morning_seal.sh`.

Update search and frontend teams

---

server.rb

Reverts binaryberry/seal#193
Reverting this for now as it causes issues for us, it seems each time we use the endpoint, it runs the seal for all the teams in our config - we think it's because we need to pass the param into the thread, otherwise the contents of the param change before the thread. So we think running Thread.start(params[:team_name]) { |team_name| ... } would solve it.

Revert "Add async calculation for server call"

---

bin/morning_seal.sh
config/alphagov.yml

We recently changed our channel name, this commit is to reflect that.
I also added Andy into our channel.

Benchmarking renamed to Modeling Services

---

config/alphagov.yml

This commit updates the email team for Q3 2017:
* Add Kevin Dew, Thomas Leese and Bevan Loon
* Remove David Basalla

Update the email team for Q3 2017

---

lib/message_builder.rb

This commit adds HTML encoding to PR titles, so the characters "&", "<" and ">" don't mess up rendering of PR titles in Slack.

HTML encode PR titles

---

config/alphagov.yml

If you click on the username it seems to be "app/dependabot" internally:
https://github.com/alphagov/feedback/pulls/app/dependabot

Possibly fix dependabot's GH username

---

bin/afternoon_seal.sh
config/alphagov.yml

A secondary channel to get visibility on code review status across the "Making it easier to find things" objective in GOV.UK.
Contains the same people as Start pages, Frontend navigation & Modelling services.

Add seal for the "Making it easier to find things" objective in GOV.UK

---

config/alphagov.yml

He's moving to Reliability Engineering

Remove Chris Patuzzo from Email team

---

bin/afternoon_seal.sh

Afternoon seal only posts quotes and this team doesn't have any defined.

Remove govuk-easier-finding from afternoon seal

---

bin/morning_seal.sh

Remove navigation team from morning seal

---

README.md
app.json
lib/github_fetcher.rb

- Added support for optionally using a custom Github API endpoint for use with Github Enterprises instances
- Param is passed in as the `GITHUB_API_ENDPOINT` environment variable

Added support for passing in Github API endpoint in env

---

config/alphagov.yml

Andrew has moved to DATA.GOV.UK.

Remove Andrew from Data Informed Content

---

config/alphagov.yml

Dean works in a dedicated Tools channel and the Seal seems to be committed to GOV.UK team members at the moment, so remove him.
Add Roch /cc @rtrinque

Delete Dean, add Roch

---

bin/morning_seal.sh

Fix platform_health reference in morning_seal

---

lib/slack_poster.rb
spec/slack_poster_spec.rb

We had an issue where our webhook was no longer able to post to arbitrary channels, due to a permissions change. Seal was failing silently.
Make Seal fail loudly

Raise an exception if Slack posting fails

---

README.md
lib/github_fetcher.rb
lib/seal.rb
spec/github_fetcher_spec.rb
spec/seal_spec.rb

Since the GitHub API now gives you review status, I felt it was prudent to suggest this.
This helps cut down the list so that only PRs that have no reviews at all get listed, as a PR with zero feedback is the blocker I'm looking to address -- its merge status or approval is less urgent in my use case.
I figured this would be useful to others, feel free to make suggestions for changes, and thank you for this cool bot!

Adds option to filter already-reviewed pull requests, regardless of approval status
